{
 "title": "Jwt-Pizza-Service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "1) HTTP requests by method per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{method=\"GET\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_total{method=\"DELETE\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_total{method=\"POST\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(requests_total{method=\"PUT\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "2) Active Users (within 15 minutes of inactivity) per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users/min"
    }
   ]
  },
  {
   "title": "4.A) CPU Percent/min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3) Authentication Attempts per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(authSuccess_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successes/min"
    },
    {
     "expr": "rate(authFailure_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures/min"
    }
   ]
  },
  {
   "title": "6) Latency in Milliseconds per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "pizzaOrderLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Order Latency ms/min"
    },
    {
     "expr": "rate(requestLatency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request Latency ms/min"
    }
   ]
  },
  {
   "title": "4.B) Memory Percentage/min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5.A) Pizzas Sold per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzaSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizzas/min"
    }
   ]
  },
  {
   "title": "5.B) Pizza Orders per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzaOrdersSuccess_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successes/min"
    },
    {
     "expr": "rate(pizzaOrdersFailed_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures/min"
    }
   ]
  },
  {
   "title": "5.C) Revenue per Minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzaRevenue_usd_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue/min"
    }
   ]
  }
 ]
}